name: nbs_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-219.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  logger: ^1.1.0
  auto_route: ^5.0.2
  build_runner: ^2.3.2
  fluttertoast: ^8.1.1
  shared_preferences: ^2.0.15
  auto_route_generator: ^5.0.3
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  json_serializable: ^6.5.3
  dio: ^4.0.6
  responsive_sizer: ^3.1.1
  flutter_gen: ^5.1.0+1
  flutter_gen_runner: any
  flutter_bloc: ^8.1.1
  shimmer_pro: ^0.0.6
  intl: ^0.18.0
  flutter_launcher_icons: ^0.11.0
  http_mock_adapter: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo/nbs.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/logo/
